name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build-userscript

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist-userscript/shiki-search.user.js
            dist-userscript/shiki-search.meta.js
